const List<List<List<String>>> spiritualCategory = [
  [
    [
      "Bodh Gaya",
      "Mahabodhi Temple",
      "Sarnath",
      "Kushinagar",
      "Sravasti",
      "Kaushambi",
    ],
    [
      "https://tse2.mm.bing.net/th?id=OIP.OxVjglTcS5Bmbi94OfL1TQHaE8&pid=Api&P=0&h=180",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/banner/bodh-gaya-mahabodhi-temple.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/varanasi/varanasi-sarnath-0.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/ayodhya/ayodhya-ramabhar-stupa-kushinagar-uttar-pradesh.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/ayodhya/ayodhya-swarna-gandha-kuti-sravasti-uttar-pradesh.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/allahabad/allahabad-kaushambi-30.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
    ],
    [
      "Legend has it that beneath the revered Bodhi tree in Bodh Gaya, Prince Siddhartha embarked on his profound meditation, ultimately attaining enlightenment and becoming the revered figure of Buddhism, Lord Buddha. Amidst this spiritual journey, a poignant moment emerged when a compassionate young cow herder named Sujata approached Siddhartha, moved by his austere countenance, and offered him a humble bowl of kheer, a sweet rice pudding. This simple act of kindness, symbolizing nourishment and care, has since been woven into the rich tapestry of Buddhist lore, echoing the profound interplay between compassion and enlightenment at the heart of the Buddhist tradition.",
      "The UNESCO-listed Mahabodhi Temple Complex, located in Bodh Gaya, Bihar, is a revered site where Lord Buddha attained enlightenment. The majestic temple, standing amidst lush greenery, features intricate sandstone architecture and houses a gilded statue of Buddha in his bhumisparsha mudra. Destroyed in the 12th century and rebuilt in the 14th, it remains a captivating testament to Buddhist heritage. Don't miss the serene lotus pond nearby.",
      "One of the most revered Buddhist pilgrimage centres in the world, Sarnath, is located just 10 km away from Varanasi. It is believed that after attaining nirvana (enlightenment), Lord Buddha delivered his first sermon here, sanctified as the Maha Dharma Chakra Pravartan Sutra. Sarnath has several structures from the time – such as the Dhamekh Stupa, which marks the spot where Lord Buddha delivered his first sermon and the Chaukhandi Stupa, where Lord Buddha met his first five disciples.",
      "Kushinagar, named after Lord Rama's son Kush, is a significant archaeological site in India. The Mahaparinirvana Temple, housing a 6-meter-long reclining Buddha idol, is a major attraction, marking where Buddha attained salvation. Explore the Kushinagar Museum for insights into the city's history, featuring Gandhara-style Buddha sculptures. Don't miss the Ramabhar Stupa, where Buddha was cremated, and the Gupta-era Sun Temple with its exquisite Sun God statue. Easily accessible from all parts of the country, Kushinagar is 188 km from Ayodhya.",
      "Sravasti, once capital of the Kosala kingdom, is a revered Buddhist pilgrimage center along the River Rapti. Highlights include the Miracle Stupa, commemorating Buddha's teachings, and other sites like Anathapindika's Stupa and the Jain tirthankara temple. The ruins of Angulimala's Stupa and Pakki Kuti showcase ancient history. Located 107 km from Ayodhya, Sravasti offers rich exploration opportunities.",
      "Kaushambi, a district carved from Prayagraj in 1997, is steeped in history. Mentioned in Hindu epics and once a hub for Buddhist teachings, it was among India's flourishing towns in Buddha's time. Puranic texts recount Nicaksu's transfer of capital from Hastinapur, revealed by excavations showcasing a grand monastery, Ashokan pillar, and ancient artifacts, affirming its rich heritage.",
    ],
  ],
  [
    [
      "Ayodhya",
      "Gokul",
      "Kedarnath",
      "Badrinath",
      "Dwarka",
      "Puri",
    ],
    [
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/ayodhya/ayodhya-guptar-ghat-30.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/mathura/mathura-vrindavan-0.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/uttarakhand/uttarakhand-kedaharnath-kedaharnath-uttarakhand.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/badrinath/Badrinath-banner.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/dwarka/dwarka-dwarkadish-temple-1.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://tse4.mm.bing.net/th?id=OIP.WpSoqr6YcpWWi8hwRrvwnwHaGE&pid=Api&P=0&h=180",
    ],
    [
      "Sprawled along the serene Saryu river, Ayodhya, in Uttar Pradesh, is one of the holiest cities of Hinduism and attracts thousands of pilgrims throughout the year. Revered as the birthplace of Lord Rama, as mentioned in the Hindu epic Ramayana, the city is dotted with temples, some of which are connected to the ghats (stepped banks of the river) of Saryu.",
      "Poised on the banks of the holy River Yamuna, the old city of Mathura, in Uttar Pradesh, is one of the most important religious destinations in India. A labyrinth of lanes lined by temples, ancient ghats and numerous stories of Lord Krishna, who is said to be born here, echoing throughout the streets, Mathura invites devotees from far and wide.",
      "Ensconced in the snow-capped Garhwal Himalayas, surrounded by a lush cover of alpine meadows and brushed by the pristine and holy Mandakini river, Kedarnath is a prominent pilgrimage spot. One of the char dhams, which are considered important pilgrimage destinations by Hindus, Kedarnath is said to be the abode of Lord Shiva, who is worshipped in the main shrine. Thousands of devotees from all over the country, undertake an arduous but devotional journey to reach this 3,584-m-high temple, which is the highest of the 12 jyotirlingas (devotional shrines of Lord Shiva) in India.",
      "A perfect blend of divinity and serenity, the picturesque town of Badrinath in Uttarakhand's Chamoli district, prides itself as one of the most visited tourist destinations of India. Considered as the abode of Lord Vishnu, Badrinath is among the holy shrines of the char Dham pilgrimage undertaken by devotees.",
      "Dwarka, Gujarat, on the Arabian Sea coast, is famed as Lord Krishna's abode. Home to the Dwarkadhish Temple and scenic Gomti creek, it offers vibrant cuisine like shrikhand and mag-ni-dal. With tranquil waters for diving, tourists can explore marine life and submerged ancient city ruins for an unforgettable experience.",
      "Puri, nestled along the Bay of Bengal in Odisha, is a revered pilgrimage site for Hindus, known for the iconic Jagannath Temple. The city comes alive during the grand Ratha Yatra festival, drawing millions of devotees. Amidst the spiritual fervor, the outskirts offer tranquil beaches and lakes, attracting nature enthusiasts seeking serenity.",
    ],
  ],
  [
    [
      "Basilica Of Bom Jesus",
      "Church Of St Francis Of Assisi",
      "Our Lady Of Immaculate Conception Church",
      "San Thomas Basilica",
      "Santa Cruz Basilica",
      "St. Francis Church",
    ],
    [
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/goa/goa-basilica-of-bom-jesus-0.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/goa/incredible-india-church-st-francis-assisi.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/goa/goa-church-of-our-lady-of-immaculate-conception-0.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/chennai/st-thomas-basalica-chennai-tamilnadu.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/kochi/santa-cruz-basilica-kochi-kerala.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/dalhousie/st-francis-church-dalhousie-himachal-pradesh.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
    ],
    [
      "Probably the most famous church in Goa and one of the most revered by Christians globally, the Basilica of Bom Jesus in Old Goa is famed for housing the mortal remains of St Francis Xavier. This complex, along with some other churches of Old Goa, features on the UNESCO World Heritage list. Its exterior facade, built using black granite, is noted for Baroque architecture combined with Doric, Corinthian and composite influences.",
      "The Church of St. Francis of Assisi, situated in Old Goa's main square and around 10 km from Panaji, was established by Franciscan friars in 1517. Combining Portuguese-Manueline and Baroque styles, its exterior boasts simplicity while the interior dazzles with Corinthian influences. The main altar, adorned with a statue of St. Francis and Jesus Christ, is flanked by wooden paintings narrating the saint's life.",
      "Located in the state capital of Panaji, Our Lady of Immaculate Conception Church is believed to have been originally built as a chapel in 1541, to serve the religious requirements of the Portuguese sailors. The chapel eventually became a parish in 1600 and nine years later, it was replaced by a church. Its symmetrical zigzag stairway was constructed in the 18th century. The church is believed to have been modelled after the Bom Jesus de Braga in Portugal, with one middle and four side landings in perfect symmetry.",
      "The Roman Catholic cathedral in Tamil Naidu, with its pristine white facade, has roots tracing back to 16th-century Portuguese origins. Rebuilt in Neo-Gothic style in 1896, it's believed to house the remains of St. Thomas the Apostle, marked by a relic and an underground tomb chapel. Adorned with a stained glass window narrating St. Thomas's story and wooden plaques depicting the stations of the cross, it also features a revered statue of Virgin Mary, brought from Portugal in 1543.",
      "Santa Cruz Basilica in Kochi, one of India's eight magnificent Basilicas, was erected by the Portuguese in 1505. With striking lofty spires and a pristine white exterior, its vividly painted interior captivates visitors. Medieval touches abound in its arches and altar, while seven canvas paintings inspired by Leonardo da Vinci's 'Last Supper' adorn its walls. Admire the mesmerizing ceiling, depicting scenes from Christ's Via Crucis, and marvel at intricate wall carvings and stained glass windows showcasing the artisans' skill.",
      "Located in Dalhousie's Subhas Chowk, the exquisite St Francis Church stands as a testament to Victorian-era architecture. Built in 1894 by British Indian Army soldiers, its stunning interior boasts intricate stonework and multicolored Belgian glass decorations, drawing art and architecture enthusiasts. Adorned with historical narrations on its interior walls, it remains a beloved spot for tourists and locals alike, maintained by the Catholic Diocese of Jalandhar and preserved by local authorities for over a century.",
    ],
  ],
  [
    [
      "Golden Temple",
      "Baba Atal Rai Tower",
      "Takht Sri Harmandir Sahib",
      "Gurudwara Bangla Sahib",
      "Nanded",
      "Gurudwara Sachkhand Sahib ",
    ],
    [
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/amritsar/amritsar-golden-temple-0.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/amritsar/amritsar-baba-atal-rai-tower-10.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/patna/patna-takht-sri-harimandir-sahib-190.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/delhi/delhi-gurdwara-bangla-sahib-10.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/nanded/nanded-sachkhand-sri-hazur-sahib-190.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/nanded/nanded-gurudwara-sachkhand-shri-hazur-sahib---nanded-entrance-wide-shot-on-dasera-nagarkirtan.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
    ],
    [
      "Amritsar is renowned for the Golden Temple, or Sri Harmandir Sahib, a revered spiritual site globally. Initiated by Maharaja Ranjit Singh in the 19th century, the temple's top half is adorned with around 400 kg of pure gold leaf, earning its English moniker. The complex, crafted predominantly in white marble, showcases intricate pietra dura motifs with precious and semi-precious stones, offering a grand and awe-inspiring sight.",
      "Baba Atal Rai Tower, located south of the Golden Temple in Amritsar, stands at 40 meters tall with nine storeys, making it one of the city's tallest structures. Legend has it that Atal Rai, son of Guru Hargobind, took samadhi here after reviving a friend and facing rebuke for his spiritual powers. Each floor represents a year of Atal's life, with the tower housing miniature works depicting scenes from Guru Nanak's life. Visitors can also enjoy panoramic views of Amritsar from the top.",
      "This gurudwara, also known as Patna Sahib, marks the birth site of Guru Gobind Singh, the last of the highly venerated 10 Sikh gurus. Situated in the bustling Harmandir Gali in Patna's old quarters in the Chowk area, this sacred shrine is now known as one of the five takhts (Sikh seats of authority) of Sikhism. It was built by Maharaja Ranjit Singh, the well-known ruler of Punjab.",
      "Gurudwara Bangla Sahib, a serene oasis in Connaught Place in Delhi, boasts a shimmering golden dome. Inside, find peace at the sanctum and by the tranquil pond. Visitors are welcomed with langar and can explore the cooking area, art gallery, and school on the premises.",
      "Nanded, Maharashtra, embodies a harmonious blend of spiritual heritage and modernity, resonating with the grace of Guru Gobind Singh, the tenth Sikh guru. Believers flock to this historic city, chosen by Guru Gobind Singh for his final congregation by the banks of the River Godavari, feeling his presence woven into its very fabric.",
      "Gurudwara Sachkhand Sahib in Nanded Maharashtra, built by Maharaja Ranjit Singh, marks where Guru Gobind Singh Ji passed away and passed on the guru-ship to the Guru Granth Sahib. Nanded is called Abchalnagar, the steadfast city, by Guru Gobind Singh Ji, emphasizing its spiritual importance. Sachkhand means the region of truth, highlighting the sanctity of the site.",
    ],
  ],
  [
    [
      "Jama Masjid",
      "Hazratbal Mosque",
      "Ajmer-E-Sharif",
      "Fatehpur Sikri",
      "Hazrat Nizamuddin Dargah",
    ],
    [
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/delhi/delhi-delhi-jama-masjid.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/srinagar/srinagar-hazrat-mosque-0.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/ajmer/ajmer-ajmer-e-sharif-0.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/agra/agra-fatehpur-sikri-0.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/delhi/delhi-hazrat-nizamuddin-aulia-30.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
    ],
    [
      "Jama Masjid, built by Shah Jahan in 1644, is one of India's largest mosques in Old Delhi. Its red sandstone and marble structure, also known as Masjid-I-Jahanuma, boasts a vast courtyard accommodating 25,000 devotees. With two towering minarets, it offers splendid views of Old Delhi's bustling streets.",
      "Situated on the left banks of Dal Lake, right opposite the Nishat Bagh, the grandiose Hazratbal shrine (mosque) is a highly revered site. The mosque is believed to house Moi-e-Muqqadas the sacred hair of Prophet Muhammad's beard. It is said to be dating back to the 17th century.",
      "Ajmer-e-Sharif, a revered Sufi shrine, honors Khwaja Moinuddin Chishti, drawing devotees worldwide located in Ajmer. Shops outside offer perfumes and sweets, while inside, a marble tomb adorned with gold and silver awaits. Evening rituals include Mehfil-e-Sama, and visitors can see the badi deg, believed to fulfill wishes.",
      "Emperor Akbar built his capital at Fatehpur Sikri between 1572 and 1585 AD, seeking blessings for a son from Sufi saint Sheikh Salim Chishti. Blessed with a son, he named the city Fatehpur Sikri  (city of victory) and his son Salim after the saint.",
      "Hazrat Nizamuddin Dargah, a prominent spiritual site in Delhi, honors the Sufi saint Nizam-ud-din Auliya. Dating back to the 14th century, it features intricate jaalis and a vast courtyard framed by marble arches, showcasing Islamic architecture. A highlight is the 13th-century room, Hujra-e-Qadeem.",
    ],
  ],
  [
    [
      "Ranakpur Temple",
      "Mount Abu",
      "Pareshnath Temple",
      "Palitana",
    ],
    [
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/udaipur/udaipur-ranakpur-130.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredibleindia/images/places/mount-abu/mount-abu-mount-abu-130.jpg/jcr:content/renditions/cq5dam.web.1800.600.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/places/kolkata/parshwanath-jain-temple-wide-garden-temple-kolkata.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
      "https://www.incredibleindia.org/content/dam/incredible-india-v2/images/banner/diu-palitana.jpg/jcr:content/renditions/cq5dam.web.1800.737.jpeg",
    ],
    [
      "Ranakpur Temple, nestled in Ranakpur village amidst the Aravalli Hills Rajasthan, is a stunning spiritual destination. The main temple, Chaumukha Mandir (four-faced temple), dedicated to Adinath, the first Jain tirthankar, holds significance for the Jain community in India.",
      "Mount Abu, Rajasthan's sole hill station, sits at 1,722 m above sea level in the Aravalli range, a three-hour drive from Udaipur. Nakki Lake, with its legend of divine origins, offers boating and views of unique rock formations like Toad Rock. Visitors also enjoy sunset views from the hilltop and exploring the nearby Raghunath Temple.",
      "Pareshnath Temple,in Kolkata dedicated to the 23rd Jain tirthankar, Pareshnath, is a revered pilgrimage site. Inside its vast complex are four temples dedicated to other avatars of the Jain faith. The main temple houses a ghee lamp lit since 1867, symbolizing purity. The temple's white marble floors represent purity and beauty.",
      "Palitana, 170 km from Diu, is famous for its Jain temples. Climbing nearly 4,000 steps over 3.5 km to the Shatrunjaya Hill top, visitors encounter 836 temples. This site holds great significance for Jains as it's where the first tirthankara, Adinath, attained enlightenment. Built by wealthy Jain businessmen, these temples date back to the 11th-16th centuries."
    ],
  ],
];
